# Generated by Django 5.2.9 on 2026-01-03 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic_saathi', '0003_sla_and_escalation_improvements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, help_text='Enter a valid 10-digit mobile number starting with 6, 7, 8, or 9', max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits and start with 6, 7, 8, or 9.', regex='^[6-9]\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='worker',
            name='address',
            field=models.TextField(),
        ),
    ]
