# Generated by Django 5.2.9 on 2026-01-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic_saathi', '0004_alter_customuser_phone_alter_worker_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('FILTERING', 'Under Filter Check'), ('DECLINED', 'Declined'), ('VERIFIED', 'Verified'), ('SORTING', 'Being Sorted'), ('PENDING', 'Pending Assignment'), ('ASSIGNED', 'Assigned to Worker'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=50),
        ),
    ]
