# Generated by Django 5.2.9 on 2025-12-14 03:35

from django.db import migrations


def copy_users_to_auth_user(apps, schema_editor):
    """Handle table naming - skip if auth_user already has the data"""
    pass  # No-op since we're using auth_user directly now


class Migration(migrations.Migration):

    dependencies = [
        ('civic_saathi', '0005_migrate_to_auth_user'),
    ]

    operations = [
        migrations.RunPython(copy_users_to_auth_user, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table=None,
        ),
    ]
