# Generated by Django 5.2.9 on 2026-01-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic_saathi', '0005_alter_complaint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='sla_deadline',
            field=models.DateTimeField(blank=True, help_text='Service Level Agreement deadline', null=True),
        ),
    ]
