# Generated by Django 5.2.9 on 2026-02-20 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic_saathi', '0006_complaint_sla_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('FILTERING', 'Under Filter Check'), ('DECLINED', 'Declined'), ('VERIFIED', 'Verified'), ('SORTING', 'Being Sorted'), ('PENDING', 'Pending Assignment'), ('ASSIGNED', 'Assigned to Worker'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('PENDING_VERIFICATION', 'Pending Manual Verification')], default='SUBMITTED', max_length=50),
        ),
        migrations.CreateModel(
            name='AIVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('YES', 'Genuine'), ('NO', 'Not Genuine'), ('ERROR', 'Verification Error (Manual Review)')], max_length=10)),
                ('description_snapshot', models.TextField(blank=True, help_text='Complaint description at the time of AI verification')),
                ('image_path_snapshot', models.CharField(blank=True, help_text='Image path used for AI verification', max_length=500)),
                ('error_detail', models.TextField(blank=True, help_text='Exception detail if AI call failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_verification_logs', to='civic_saathi.complaint')),
            ],
            options={
                'verbose_name': 'AI Verification Log',
                'verbose_name_plural': 'AI Verification Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
