# Generated by Django 5.2.9 on 2026-02-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic_saathi', '0007_alter_complaint_status_aiverificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='smart_hash',
            field=models.CharField(blank=True, db_index=True, help_text='10-char smart hash [TITLE3][LAT2][LON2][DEPT3] for duplicate detection', max_length=10),
        ),
    ]
