# Generated by Django 4.2.28 on 2026-02-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic_saathi', '0009_worker_notification_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiverificationlog',
            name='ai_emergency',
            field=models.BooleanField(default=False, help_text='AI flagged as emergency'),
        ),
        migrations.AddField(
            model_name='aiverificationlog',
            name='ai_priority',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Priority level recommended by AI (1-5)', null=True),
        ),
        migrations.AddField(
            model_name='aiverificationlog',
            name='ai_sla_hours',
            field=models.PositiveIntegerField(blank=True, help_text='SLA hours recommended by AI', null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_emergency',
            field=models.BooleanField(default=False, help_text='AI flagged as emergency — immediate attention required'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='priority_level',
            field=models.PositiveSmallIntegerField(default=1, help_text='AI-determined base priority: 1=Minimal, 2=Low, 3=Medium, 4=High, 5=Emergency'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='sla_hours',
            field=models.PositiveIntegerField(default=48, help_text='AI-determined SLA hours based on severity (2-48h)'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='priority',
            field=models.PositiveSmallIntegerField(default=1, help_text='1=Minimal, 2=Low, 3=Medium, 4=High, 5=Emergency (AI-determined + votes)'),
        ),
    ]
